
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../android_webview/browser/aw_settings.h

package org.chromium.android_webview.settings;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ForceDarkBehavior.FORCE_DARK_ONLY, ForceDarkBehavior.MEDIA_QUERY_ONLY,
    ForceDarkBehavior.PREFER_MEDIA_QUERY_OVER_FORCE_DARK
})
@Retention(RetentionPolicy.SOURCE)
public @interface ForceDarkBehavior {
  int FORCE_DARK_ONLY = 0;
  int MEDIA_QUERY_ONLY = 1;
  int PREFER_MEDIA_QUERY_OVER_FORCE_DARK = 2;
}
