
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../media/capture/video/android/photo_capabilities.h

package org.chromium.media;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    MeteringModeType.FOCUS, MeteringModeType.EXPOSURE, MeteringModeType.WHITE_BALANCE
})
@Retention(RetentionPolicy.SOURCE)
public @interface MeteringModeType {
  int FOCUS = 0;
  int EXPOSURE = 1;
  int WHITE_BALANCE = 2;
  int NUM_ENTRIES = 3;
}
