
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/capture/mojom/video_capture_types.mojom
//

package org.chromium.media.mojom;

import org.chromium.mojo.bindings.DeserializationException;

public final class ResolutionChangePolicy {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int FIXED_RESOLUTION = 0;
    public static final int FIXED_ASPECT_RATIO = 1; // FIXED_RESOLUTION + 1
    public static final int ANY_WITHIN_LIMIT = 2; // FIXED_ASPECT_RATIO + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 2;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new DeserializationException("Invalid enum value.");
    }

    private ResolutionChangePolicy() {}
}