// VideoCaptureBufferType.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/capture/mojom/video_capture_types.mojom
//

package org.chromium.media.mojom;

import androidx.annotation.IntDef;

public final class VideoCaptureBufferType {
    private static final boolean IS_EXTENSIBLE = true;
    @IntDef({

        VideoCaptureBufferType.SHARED_MEMORY,
        VideoCaptureBufferType.SHARED_MEMORY_VIA_RAW_FILE_DESCRIPTOR,
        VideoCaptureBufferType.MAILBOX_HOLDER,
        VideoCaptureBufferType.GPU_MEMORY_BUFFER})
    public @interface EnumType {}

    public static final int SHARED_MEMORY = 0;
    public static final int SHARED_MEMORY_VIA_RAW_FILE_DESCRIPTOR = 1;
    public static final int MAILBOX_HOLDER = 2;
    public static final int GPU_MEMORY_BUFFER = 3;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 3;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 3;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private VideoCaptureBufferType() {}
}