
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/capture/mojom/video_capture.mojom
//

package org.chromium.media.mojom;

import org.chromium.mojo.bindings.DeserializationException;

public final class VideoCaptureState {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int STARTED = 0;
    public static final int PAUSED = 1; // STARTED + 1
    public static final int RESUMED = 2; // PAUSED + 1
    public static final int STOPPED = 3; // RESUMED + 1
    public static final int FAILED = 4; // STOPPED + 1
    public static final int ENDED = 5; // FAILED + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 5;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new DeserializationException("Invalid enum value.");
    }

    private VideoCaptureState() {}
}