// GenericAssociatedInterface.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     mojo/public/mojom/base/generic_pending_associated_receiver.mojom
//

package org.chromium.mojo_base.mojom;

import androidx.annotation.IntDef;


public interface GenericAssociatedInterface extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends GenericAssociatedInterface, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<GenericAssociatedInterface, GenericAssociatedInterface.Proxy> MANAGER = GenericAssociatedInterface_Internal.MANAGER;

}
