// AuthenticatorStatus.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/webauthn/authenticator.mojom
//

package org.chromium.blink.mojom;

public final class AuthenticatorStatus {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int SUCCESS = 0;
    public static final int PENDING_REQUEST = 1;
    public static final int NOT_ALLOWED_ERROR = 2;
    public static final int INVALID_DOMAIN = 3;
    public static final int INVALID_ICON_URL = 4;
    public static final int CREDENTIAL_EXCLUDED = 5;
    public static final int CREDENTIAL_NOT_RECOGNIZED = 6;
    public static final int NOT_IMPLEMENTED = 7;
    public static final int NOT_FOCUSED = 8;
    public static final int RESIDENT_CREDENTIALS_UNSUPPORTED = 9;
    public static final int USER_VERIFICATION_UNSUPPORTED = 10;
    public static final int ALGORITHM_UNSUPPORTED = 11;
    public static final int EMPTY_ALLOW_CREDENTIALS = 12;
    public static final int ANDROID_NOT_SUPPORTED_ERROR = 13;
    public static final int PROTECTION_POLICY_INCONSISTENT = 14;
    public static final int ABORT_ERROR = 15;
    public static final int OPAQUE_DOMAIN = 16;
    public static final int INVALID_PROTOCOL = 17;
    public static final int BAD_RELYING_PARTY_ID = 18;
    public static final int CANNOT_READ_AND_WRITE_LARGE_BLOB = 19;
    public static final int INVALID_ALLOW_CREDENTIALS_FOR_LARGE_BLOB = 20;
    public static final int UNKNOWN_ERROR = 21;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 21;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 21;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private AuthenticatorStatus() {}
}