// SpeechRecognitionErrorCode.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/speech/speech_recognition_error_code.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;

public final class SpeechRecognitionErrorCode {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        SpeechRecognitionErrorCode.NONE,
        SpeechRecognitionErrorCode.NO_SPEECH,
        SpeechRecognitionErrorCode.ABORTED,
        SpeechRecognitionErrorCode.AUDIO_CAPTURE,
        SpeechRecognitionErrorCode.NETWORK,
        SpeechRecognitionErrorCode.NOT_ALLOWED,
        SpeechRecognitionErrorCode.SERVICE_NOT_ALLOWED,
        SpeechRecognitionErrorCode.BAD_GRAMMAR,
        SpeechRecognitionErrorCode.LANGUAGE_NOT_SUPPORTED,
        SpeechRecognitionErrorCode.NO_MATCH})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int NO_SPEECH = 1;
    public static final int ABORTED = 2;
    public static final int AUDIO_CAPTURE = 3;
    public static final int NETWORK = 4;
    public static final int NOT_ALLOWED = 5;
    public static final int SERVICE_NOT_ALLOWED = 6;
    public static final int BAD_GRAMMAR = 7;
    public static final int LANGUAGE_NOT_SUPPORTED = 8;
    public static final int NO_MATCH = 9;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 9;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 9;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private SpeechRecognitionErrorCode() {}
}