// ShapeDetectionService.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/shape_detection/public/mojom/shape_detection_service.mojom
//

package org.chromium.shape_detection.mojom;

import androidx.annotation.IntDef;


public interface ShapeDetectionService extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends ShapeDetectionService, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<ShapeDetectionService, ShapeDetectionService.Proxy> MANAGER = ShapeDetectionService_Internal.MANAGER;


    void bindBarcodeDetectionProvider(
org.chromium.mojo.bindings.InterfaceRequest<BarcodeDetectionProvider> receiver);



    void bindFaceDetectionProvider(
org.chromium.mojo.bindings.InterfaceRequest<FaceDetectionProvider> receiver);



    void bindTextDetection(
org.chromium.mojo.bindings.InterfaceRequest<TextDetection> receiver);


}
