package org.chromium.base.library_loader;
import org.chromium.base.annotations.SuppressFBWarnings;
@SuppressFBWarnings
public class NativeLibraries {
    public static boolean sUseLinker = false;
    public static boolean sUseLibraryInZipFile = false;
    public static boolean sEnableLinkerTests = false;
    public static final String[] LIBRARIES =
      {"standalonelibwebviewchromium","drawgl"};
//      {"gfx_switches.cr","mojo_public_system.cr","c++_shared","drawgl.cr","base.cr","ffmpeg.cr","device_event_log.cr","gles2_c_lib.cr","sandbox_services.cr","platform.cr","prefs.cr","mojo_public_system_cpp.cr","v8_libbase.cr","range.cr","gles2_utils.cr","geometry.cr","events_base.cr","protobuf_lite.cr","user_prefs.cr","seccomp_bpf.cr","viz_resource_format.cr","icuuc.cr","seccomp_starter_android.cr","device_base.cr","mojo_common_lib.cr","keyed_service_core.cr","bindings.cr","boringssl.cr","service_manager_mojom_shared.cr","interfaces_shared.cr","url.cr","device_gamepad.cr","url_ipc.cr","sensors.cr","crcrypto.cr","discardable_memory_common.cr","policy_proto.cr","ui_data_pack.cr","startup_tracing.cr","freetype.cr","resource_coordinator_public_interfaces_internal_shared.cr","icui18n.cr","blink_android_mojo_bindings_shared.cr","discardable_memory_client.cr","chromium_sqlite3.cr","cloud_policy_proto_generated_compile.cr","v8.cr","fingerprint.cr","display_types.cr","device_vr_mojo_bindings_shared.cr","wtf.cr","display_util.cr","sql.cr","shared_memory_support.cr","discardable_memory_service.cr","ipc_mojom_shared.cr","service_manager_mojom_constants_shared.cr","url_matcher.cr","metrics_cpp.cr","skia.cr","content_public_common_mojo_bindings_shared.cr","mojo_system_impl.cr","service_manager_mojom_blink.cr","gin.cr","blink_offscreen_canvas_mojo_bindings_shared.cr","webdata_common.cr","base_i18n.cr","blink_mojo_bindings_shared.cr","service_manager_mojom_constants.cr","service_manager_cpp_types.cr","color_space.cr","display.cr","geometry_skia.cr","service_manager_mojom_constants_blink.cr","ipc_mojom.cr","content_common_mojo_bindings_shared.cr","surface.cr","codec.cr","animation.cr","net.cr","js.cr","cc_debug.cr","midi.cr","geolocation.cr","service_manager_mojom.cr","proxy_config.cr","devices.cr","ipc.cr","cc_base.cr","storage_common.cr","gfx_ipc_skia.cr","gfx_ipc_geometry.cr","service_manager_cpp.cr","tracing.cr","gfx_ipc_color.cr","storage_browser.cr","cc_paint.cr","gfx.cr","resource_coordinator_cpp.cr","gfx_ipc.cr","ui_touch_selection.cr","gesture_detection.cr","gl_wrapper.cr","events.cr","ui_base.cr","bluetooth.cr","policy_component.cr","printing.cr","accessibility.cr","ui_base_ime.cr","embedder.cr","native_theme.cr","gl_init.cr","gpu.cr","media.cr","device_vr_mojo_bindings_blink.cr","device_vr_mojo_bindings.cr","cdm_manager.cr","gles2_implementation.cr","capture_base.cr","capture_lib.cr","blink_common.cr","gl_in_process_context.cr","media_gpu.cr","device_vr.cr","viz_common.cr","media_mojo_services.cr","snapshot.cr","cc.cr","cc_ipc.cr","service.cr","cc_animation.cr","host.cr","ui_android.cr","shell_dialogs.cr","blink_platform.cr","blink_core.cr","blink_modules.cr","blink_controller.cr","cc_blink.cr","media_blink.cr","content.cr","standalonelibwebviewchromium.cr"};
    static String sVersionNumber =
      "62.0.3202.101";
}
