// CoopAccessReportType.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/cross_origin_opener_policy.mojom
//

package org.chromium.network.mojom;

import androidx.annotation.IntDef;

public final class CoopAccessReportType {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        CoopAccessReportType.ACCESS_FROM_COOP_PAGE_TO_OPENER,
        CoopAccessReportType.ACCESS_FROM_COOP_PAGE_TO_OPENEE,
        CoopAccessReportType.ACCESS_FROM_COOP_PAGE_TO_OTHER,
        CoopAccessReportType.ACCESS_TO_COOP_PAGE_FROM_OPENER,
        CoopAccessReportType.ACCESS_TO_COOP_PAGE_FROM_OPENEE,
        CoopAccessReportType.ACCESS_TO_COOP_PAGE_FROM_OTHER})
    public @interface EnumType {}

    public static final int ACCESS_FROM_COOP_PAGE_TO_OPENER = 0;
    public static final int ACCESS_FROM_COOP_PAGE_TO_OPENEE = 1;
    public static final int ACCESS_FROM_COOP_PAGE_TO_OTHER = 2;
    public static final int ACCESS_TO_COOP_PAGE_FROM_OPENER = 3;
    public static final int ACCESS_TO_COOP_PAGE_FROM_OPENEE = 4;
    public static final int ACCESS_TO_COOP_PAGE_FROM_OTHER = 5;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 5;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 5;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private CoopAccessReportType() {}
}