// CrossOriginOpenerPolicyValue.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/cross_origin_opener_policy.mojom
//

package org.chromium.network.mojom;

import androidx.annotation.IntDef;

public final class CrossOriginOpenerPolicyValue {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        CrossOriginOpenerPolicyValue.SAME_ORIGIN,
        CrossOriginOpenerPolicyValue.SAME_ORIGIN_ALLOW_POPUPS,
        CrossOriginOpenerPolicyValue.UNSAFE_NONE,
        CrossOriginOpenerPolicyValue.SAME_ORIGIN_PLUS_COEP})
    public @interface EnumType {}

    public static final int SAME_ORIGIN = 0;
    public static final int SAME_ORIGIN_ALLOW_POPUPS = 1;
    public static final int UNSAFE_NONE = 2;
    public static final int SAME_ORIGIN_PLUS_COEP = 3;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 3;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 3;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private CrossOriginOpenerPolicyValue() {}
}