// CspDirectiveName.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/content_security_policy.mojom
//

package org.chromium.network.mojom;

public final class CspDirectiveName {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int UNKNOWN = 0;
    public static final int DEFAULT_SRC = 1;
    public static final int CHILD_SRC = 2;
    public static final int FRAME_SRC = 3;
    public static final int FORM_ACTION = 4;
    public static final int NAVIGATE_TO = 5;
    public static final int FRAME_ANCESTORS = 6;
    public static final int IMG_SRC = 7;
    public static final int MEDIA_SRC = 8;
    public static final int OBJECT_SRC = 9;
    public static final int SCRIPT_SRC = 10;
    public static final int STYLE_SRC = 11;
    public static final int WORKER_SRC = 12;
    public static final int CONNECT_SRC = 13;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 13;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private CspDirectiveName() {}
}