// CspHashAlgorithm.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/content_security_policy.mojom
//

package org.chromium.network.mojom;

import androidx.annotation.IntDef;

public final class CspHashAlgorithm {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        CspHashAlgorithm.NONE,
        CspHashAlgorithm.SHA256,
        CspHashAlgorithm.SHA384,
        CspHashAlgorithm.SHA512})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int SHA256 = 1;
    public static final int SHA384 = 2;
    public static final int SHA512 = 4;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 4;

    public static boolean isKnownValue(int value) {
        switch (value) {
            case 0:
            case 1:
            case 2:
            case 4:
                return true;
        }
        return false;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private CspHashAlgorithm() {}
}