// RequestPriority.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/url_request.mojom
//

package org.chromium.network.mojom;

import androidx.annotation.IntDef;

public final class RequestPriority {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        RequestPriority.THROTTLED,
        RequestPriority.IDLE,
        RequestPriority.LOWEST,
        RequestPriority.LOW,
        RequestPriority.MEDIUM,
        RequestPriority.HIGHEST})
    public @interface EnumType {}

    public static final int THROTTLED = 0;
    public static final int IDLE = 1;
    public static final int LOWEST = 2;
    public static final int LOW = 3;
    public static final int MEDIUM = 4;
    public static final int HIGHEST = 5;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 5;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 5;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private RequestPriority() {}
}