// UrlLoader.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/url_loader.mojom
//

package org.chromium.network.mojom;

import androidx.annotation.IntDef;


public interface UrlLoader extends org.chromium.mojo.bindings.Interface {


    
    public static final int CLIENT_DISCONNECT_REASON = (int) 1;




    public interface Proxy extends UrlLoader, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<UrlLoader, UrlLoader.Proxy> MANAGER = UrlLoader_Internal.MANAGER;


    void followRedirect(
String[] removedHeaders, HttpRequestHeaders modifiedHeaders, HttpRequestHeaders modifiedCorsExemptHeaders, org.chromium.url.mojom.Url newUrl);



    void setPriority(
int priority, int intraPriorityValue);



    void pauseReadingBodyFromNet(
);



    void resumeReadingBodyFromNet(
);


}
