
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../third_party/blink/public/mojom/context_menu/context_menu.mojom

package org.chromium.blink_public.common;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ContextMenuDataMediaType.NONE, ContextMenuDataMediaType.IMAGE, ContextMenuDataMediaType.VIDEO,
    ContextMenuDataMediaType.AUDIO, ContextMenuDataMediaType.CANVAS, ContextMenuDataMediaType.FILE,
    ContextMenuDataMediaType.PLUGIN
})
@Retention(RetentionPolicy.SOURCE)
public @interface ContextMenuDataMediaType {
  /**
   * No special node is in context.
   */
  int NONE = 0;
  /**
   * An image node is selected.
   */
  int IMAGE = 1;
  /**
   * A video node is selected.
   */
  int VIDEO = 2;
  /**
   * An audio node is selected.
   */
  int AUDIO = 3;
  /**
   * A canvas node is selected.
   */
  int CANVAS = 4;
  /**
   * A file node is selected.
   */
  int FILE = 5;
  /**
   * A plugin node is selected.
   */
  int PLUGIN = 6;
}
