
// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/component_updater/android/component_loader_policy.h

package org.chromium.components.component_updater;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ComponentLoadResult.COMPONENT_LOADED,
    ComponentLoadResult.FAILED_TO_CONNECT_TO_COMPONENTS_PROVIDER_SERVICE,
    ComponentLoadResult.REMOTE_EXCEPTION, ComponentLoadResult.COMPONENTS_PROVIDER_SERVICE_ERROR,
    ComponentLoadResult.MISSING_MANIFEST, ComponentLoadResult.MALFORMED_MANIFEST,
    ComponentLoadResult.INVALID_VERSION, ComponentLoadResult.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface ComponentLoadResult {
  int COMPONENT_LOADED = 0;
  int FAILED_TO_CONNECT_TO_COMPONENTS_PROVIDER_SERVICE = 1;
  int REMOTE_EXCEPTION = 2;
  int COMPONENTS_PROVIDER_SERVICE_ERROR = 3;
  int MISSING_MANIFEST = 4;
  int MALFORMED_MANIFEST = 5;
  int INVALID_VERSION = 6;
  int MAX_VALUE = INVALID_VERSION;
}
