
// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/autofill/core/common/submission_source.h

package org.chromium.components.autofill;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    SubmissionSource.NONE, SubmissionSource.SAME_DOCUMENT_NAVIGATION,
    SubmissionSource.XHR_SUCCEEDED, SubmissionSource.FRAME_DETACHED,
    SubmissionSource.DOM_MUTATION_AFTER_XHR, SubmissionSource.PROBABLY_FORM_SUBMITTED,
    SubmissionSource.FORM_SUBMISSION
})
@Retention(RetentionPolicy.SOURCE)
public @interface SubmissionSource {
  int NONE = 0;
  int SAME_DOCUMENT_NAVIGATION = 1;
  /**
   * navigation.
   */
  int XHR_SUCCEEDED = 2;
  int FRAME_DETACHED = 3;
  int DOM_MUTATION_AFTER_XHR = 4;
  int PROBABLY_FORM_SUBMITTED = 5;
  /**
   * is loaded.
   */
  int FORM_SUBMISSION = 6;
}
