// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer_event.proto

package org.chromium.components.metrics;

public final class PrinterEventProtos {
  private PrinterEventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PrinterEventProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:metrics.PrinterEventProto)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @return Whether the usbPrinterManufacturer field is set.
     */
    boolean hasUsbPrinterManufacturer();
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @return The usbPrinterManufacturer.
     */
    java.lang.String getUsbPrinterManufacturer();
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @return The bytes for usbPrinterManufacturer.
     */
    com.google.protobuf.ByteString
        getUsbPrinterManufacturerBytes();

    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @return Whether the usbPrinterModel field is set.
     */
    boolean hasUsbPrinterModel();
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @return The usbPrinterModel.
     */
    java.lang.String getUsbPrinterModel();
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @return The bytes for usbPrinterModel.
     */
    com.google.protobuf.ByteString
        getUsbPrinterModelBytes();

    /**
     * <pre>
     * The usb vendor id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_vendor_id = 3;</code>
     * @return Whether the usbVendorId field is set.
     */
    boolean hasUsbVendorId();
    /**
     * <pre>
     * The usb vendor id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_vendor_id = 3;</code>
     * @return The usbVendorId.
     */
    int getUsbVendorId();

    /**
     * <pre>
     * The usb model id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_model_id = 4;</code>
     * @return Whether the usbModelId field is set.
     */
    boolean hasUsbModelId();
    /**
     * <pre>
     * The usb model id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_model_id = 4;</code>
     * @return The usbModelId.
     */
    int getUsbModelId();

    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @return Whether the ippMakeAndModel field is set.
     */
    boolean hasIppMakeAndModel();
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @return The ippMakeAndModel.
     */
    java.lang.String getIppMakeAndModel();
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @return The bytes for ippMakeAndModel.
     */
    com.google.protobuf.ByteString
        getIppMakeAndModelBytes();

    /**
     * <pre>
     * A true value means that the user provided their own PPD.
     * </pre>
     *
     * <code>optional bool user_ppd = 6;</code>
     * @return Whether the userPpd field is set.
     */
    boolean hasUserPpd();
    /**
     * <pre>
     * A true value means that the user provided their own PPD.
     * </pre>
     *
     * <code>optional bool user_ppd = 6;</code>
     * @return The userPpd.
     */
    boolean getUserPpd();

    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @return Whether the ppdIdentifier field is set.
     */
    boolean hasPpdIdentifier();
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @return The ppdIdentifier.
     */
    java.lang.String getPpdIdentifier();
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @return The bytes for ppdIdentifier.
     */
    com.google.protobuf.ByteString
        getPpdIdentifierBytes();

    /**
     * <pre>
     * The event for which this was recorded.
     * </pre>
     *
     * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
     * @return Whether the eventType field is set.
     */
    boolean hasEventType();
    /**
     * <pre>
     * The event for which this was recorded.
     * </pre>
     *
     * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
     * @return The eventType.
     */
    org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType getEventType();
  }
  /**
   * <pre>
   * Stores information about a printer that a user is setting up/has attempted to
   * set up.
   * Next tag: 9
   * </pre>
   *
   * Protobuf type {@code metrics.PrinterEventProto}
   */
  public  static final class PrinterEventProto extends
      com.google.protobuf.GeneratedMessageLite<
          PrinterEventProto, PrinterEventProto.Builder> implements
      // @@protoc_insertion_point(message_implements:metrics.PrinterEventProto)
      PrinterEventProtoOrBuilder {
    private PrinterEventProto() {
      usbPrinterManufacturer_ = "";
      usbPrinterModel_ = "";
      ippMakeAndModel_ = "";
      ppdIdentifier_ = "";
    }
    /**
     * <pre>
     * The action for which the printer was logged.
     * Next tag: 5
     * </pre>
     *
     * Protobuf enum {@code metrics.PrinterEventProto.EventType}
     */
    public enum EventType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <pre>
       * Specified printer successfully installed using the detected
       * configuration.
       * </pre>
       *
       * <code>SETUP_AUTOMATIC = 1;</code>
       */
      SETUP_AUTOMATIC(1),
      /**
       * <pre>
       * Specified printer was installed when the user selected the appropriate
       * configuration.
       * </pre>
       *
       * <code>SETUP_MANUAL = 2;</code>
       */
      SETUP_MANUAL(2),
      /**
       * <pre>
       * Setup was started but abandoned when user was prompted to choose a
       * configuration.
       * </pre>
       *
       * <code>SETUP_ABANDONED = 3;</code>
       */
      SETUP_ABANDONED(3),
      /**
       * <pre>
       * A printer, which had been successfully installed, was deleted from the
       * user's preferences.
       * </pre>
       *
       * <code>PRINTER_DELETED = 4;</code>
       */
      PRINTER_DELETED(4),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * Specified printer successfully installed using the detected
       * configuration.
       * </pre>
       *
       * <code>SETUP_AUTOMATIC = 1;</code>
       */
      public static final int SETUP_AUTOMATIC_VALUE = 1;
      /**
       * <pre>
       * Specified printer was installed when the user selected the appropriate
       * configuration.
       * </pre>
       *
       * <code>SETUP_MANUAL = 2;</code>
       */
      public static final int SETUP_MANUAL_VALUE = 2;
      /**
       * <pre>
       * Setup was started but abandoned when user was prompted to choose a
       * configuration.
       * </pre>
       *
       * <code>SETUP_ABANDONED = 3;</code>
       */
      public static final int SETUP_ABANDONED_VALUE = 3;
      /**
       * <pre>
       * A printer, which had been successfully installed, was deleted from the
       * user's preferences.
       * </pre>
       *
       * <code>PRINTER_DELETED = 4;</code>
       */
      public static final int PRINTER_DELETED_VALUE = 4;


      @java.lang.Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventType valueOf(int value) {
        return forNumber(value);
      }

      public static EventType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return SETUP_AUTOMATIC;
          case 2: return SETUP_MANUAL;
          case 3: return SETUP_ABANDONED;
          case 4: return PRINTER_DELETED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EventType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              @java.lang.Override
              public EventType findValueByNumber(int number) {
                return EventType.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return EventTypeVerifier.INSTANCE;
      }

      private static final class EventTypeVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new EventTypeVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return EventType.forNumber(number) != null;
              }
            };

      private final int value;

      private EventType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:metrics.PrinterEventProto.EventType)
    }

    private int bitField0_;
    public static final int USB_PRINTER_MANUFACTURER_FIELD_NUMBER = 1;
    private java.lang.String usbPrinterManufacturer_;
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @return Whether the usbPrinterManufacturer field is set.
     */
    @java.lang.Override
    public boolean hasUsbPrinterManufacturer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @return The usbPrinterManufacturer.
     */
    @java.lang.Override
    public java.lang.String getUsbPrinterManufacturer() {
      return usbPrinterManufacturer_;
    }
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @return The bytes for usbPrinterManufacturer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsbPrinterManufacturerBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(usbPrinterManufacturer_);
    }
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @param value The usbPrinterManufacturer to set.
     */
    private void setUsbPrinterManufacturer(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000001;
      usbPrinterManufacturer_ = value;
    }
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     */
    private void clearUsbPrinterManufacturer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      usbPrinterManufacturer_ = getDefaultInstance().getUsbPrinterManufacturer();
    }
    /**
     * <pre>
     * The detected printer manufacuter name.
     * </pre>
     *
     * <code>optional string usb_printer_manufacturer = 1;</code>
     * @param value The bytes for usbPrinterManufacturer to set.
     */
    private void setUsbPrinterManufacturerBytes(
        com.google.protobuf.ByteString value) {
      usbPrinterManufacturer_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int USB_PRINTER_MODEL_FIELD_NUMBER = 2;
    private java.lang.String usbPrinterModel_;
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @return Whether the usbPrinterModel field is set.
     */
    @java.lang.Override
    public boolean hasUsbPrinterModel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @return The usbPrinterModel.
     */
    @java.lang.Override
    public java.lang.String getUsbPrinterModel() {
      return usbPrinterModel_;
    }
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @return The bytes for usbPrinterModel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsbPrinterModelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(usbPrinterModel_);
    }
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @param value The usbPrinterModel to set.
     */
    private void setUsbPrinterModel(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000002;
      usbPrinterModel_ = value;
    }
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     */
    private void clearUsbPrinterModel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      usbPrinterModel_ = getDefaultInstance().getUsbPrinterModel();
    }
    /**
     * <pre>
     * The detected printer model name.
     * </pre>
     *
     * <code>optional string usb_printer_model = 2;</code>
     * @param value The bytes for usbPrinterModel to set.
     */
    private void setUsbPrinterModelBytes(
        com.google.protobuf.ByteString value) {
      usbPrinterModel_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int USB_VENDOR_ID_FIELD_NUMBER = 3;
    private int usbVendorId_;
    /**
     * <pre>
     * The usb vendor id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_vendor_id = 3;</code>
     * @return Whether the usbVendorId field is set.
     */
    @java.lang.Override
    public boolean hasUsbVendorId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The usb vendor id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_vendor_id = 3;</code>
     * @return The usbVendorId.
     */
    @java.lang.Override
    public int getUsbVendorId() {
      return usbVendorId_;
    }
    /**
     * <pre>
     * The usb vendor id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_vendor_id = 3;</code>
     * @param value The usbVendorId to set.
     */
    private void setUsbVendorId(int value) {
      bitField0_ |= 0x00000004;
      usbVendorId_ = value;
    }
    /**
     * <pre>
     * The usb vendor id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_vendor_id = 3;</code>
     */
    private void clearUsbVendorId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      usbVendorId_ = 0;
    }

    public static final int USB_MODEL_ID_FIELD_NUMBER = 4;
    private int usbModelId_;
    /**
     * <pre>
     * The usb model id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_model_id = 4;</code>
     * @return Whether the usbModelId field is set.
     */
    @java.lang.Override
    public boolean hasUsbModelId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The usb model id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_model_id = 4;</code>
     * @return The usbModelId.
     */
    @java.lang.Override
    public int getUsbModelId() {
      return usbModelId_;
    }
    /**
     * <pre>
     * The usb model id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_model_id = 4;</code>
     * @param value The usbModelId to set.
     */
    private void setUsbModelId(int value) {
      bitField0_ |= 0x00000008;
      usbModelId_ = value;
    }
    /**
     * <pre>
     * The usb model id of the printer.
     * </pre>
     *
     * <code>optional int32 usb_model_id = 4;</code>
     */
    private void clearUsbModelId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      usbModelId_ = 0;
    }

    public static final int IPP_MAKE_AND_MODEL_FIELD_NUMBER = 5;
    private java.lang.String ippMakeAndModel_;
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @return Whether the ippMakeAndModel field is set.
     */
    @java.lang.Override
    public boolean hasIppMakeAndModel() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @return The ippMakeAndModel.
     */
    @java.lang.Override
    public java.lang.String getIppMakeAndModel() {
      return ippMakeAndModel_;
    }
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @return The bytes for ippMakeAndModel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIppMakeAndModelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ippMakeAndModel_);
    }
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @param value The ippMakeAndModel to set.
     */
    private void setIppMakeAndModel(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000010;
      ippMakeAndModel_ = value;
    }
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     */
    private void clearIppMakeAndModel() {
      bitField0_ = (bitField0_ & ~0x00000010);
      ippMakeAndModel_ = getDefaultInstance().getIppMakeAndModel();
    }
    /**
     * <pre>
     * The value reported as a printer's printer-make-and-model attribute.
     * </pre>
     *
     * <code>optional string ipp_make_and_model = 5;</code>
     * @param value The bytes for ippMakeAndModel to set.
     */
    private void setIppMakeAndModelBytes(
        com.google.protobuf.ByteString value) {
      ippMakeAndModel_ = value.toStringUtf8();
      bitField0_ |= 0x00000010;
    }

    public static final int USER_PPD_FIELD_NUMBER = 6;
    private boolean userPpd_;
    /**
     * <pre>
     * A true value means that the user provided their own PPD.
     * </pre>
     *
     * <code>optional bool user_ppd = 6;</code>
     * @return Whether the userPpd field is set.
     */
    @java.lang.Override
    public boolean hasUserPpd() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * A true value means that the user provided their own PPD.
     * </pre>
     *
     * <code>optional bool user_ppd = 6;</code>
     * @return The userPpd.
     */
    @java.lang.Override
    public boolean getUserPpd() {
      return userPpd_;
    }
    /**
     * <pre>
     * A true value means that the user provided their own PPD.
     * </pre>
     *
     * <code>optional bool user_ppd = 6;</code>
     * @param value The userPpd to set.
     */
    private void setUserPpd(boolean value) {
      bitField0_ |= 0x00000020;
      userPpd_ = value;
    }
    /**
     * <pre>
     * A true value means that the user provided their own PPD.
     * </pre>
     *
     * <code>optional bool user_ppd = 6;</code>
     */
    private void clearUserPpd() {
      bitField0_ = (bitField0_ & ~0x00000020);
      userPpd_ = false;
    }

    public static final int PPD_IDENTIFIER_FIELD_NUMBER = 7;
    private java.lang.String ppdIdentifier_;
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @return Whether the ppdIdentifier field is set.
     */
    @java.lang.Override
    public boolean hasPpdIdentifier() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @return The ppdIdentifier.
     */
    @java.lang.Override
    public java.lang.String getPpdIdentifier() {
      return ppdIdentifier_;
    }
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @return The bytes for ppdIdentifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPpdIdentifierBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ppdIdentifier_);
    }
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @param value The ppdIdentifier to set.
     */
    private void setPpdIdentifier(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000040;
      ppdIdentifier_ = value;
    }
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     */
    private void clearPpdIdentifier() {
      bitField0_ = (bitField0_ & ~0x00000040);
      ppdIdentifier_ = getDefaultInstance().getPpdIdentifier();
    }
    /**
     * <pre>
     * The identifier for PPDs from our serving system.
     * </pre>
     *
     * <code>optional string ppd_identifier = 7;</code>
     * @param value The bytes for ppdIdentifier to set.
     */
    private void setPpdIdentifierBytes(
        com.google.protobuf.ByteString value) {
      ppdIdentifier_ = value.toStringUtf8();
      bitField0_ |= 0x00000040;
    }

    public static final int EVENT_TYPE_FIELD_NUMBER = 8;
    private int eventType_;
    /**
     * <pre>
     * The event for which this was recorded.
     * </pre>
     *
     * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
     * @return Whether the eventType field is set.
     */
    @java.lang.Override
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * The event for which this was recorded.
     * </pre>
     *
     * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType getEventType() {
      org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType result = org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType.forNumber(eventType_);
      return result == null ? org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType.UNKNOWN : result;
    }
    /**
     * <pre>
     * The event for which this was recorded.
     * </pre>
     *
     * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
     * @param value The eventType to set.
     */
    private void setEventType(org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType value) {
      eventType_ = value.getNumber();
      bitField0_ |= 0x00000080;
    }
    /**
     * <pre>
     * The event for which this was recorded.
     * </pre>
     *
     * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
     */
    private void clearEventType() {
      bitField0_ = (bitField0_ & ~0x00000080);
      eventType_ = 0;
    }

    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Stores information about a printer that a user is setting up/has attempted to
     * set up.
     * Next tag: 9
     * </pre>
     *
     * Protobuf type {@code metrics.PrinterEventProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto, Builder> implements
        // @@protoc_insertion_point(builder_implements:metrics.PrinterEventProto)
        org.chromium.components.metrics.PrinterEventProtos.PrinterEventProtoOrBuilder {
      // Construct using org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The detected printer manufacuter name.
       * </pre>
       *
       * <code>optional string usb_printer_manufacturer = 1;</code>
       * @return Whether the usbPrinterManufacturer field is set.
       */
      @java.lang.Override
      public boolean hasUsbPrinterManufacturer() {
        return instance.hasUsbPrinterManufacturer();
      }
      /**
       * <pre>
       * The detected printer manufacuter name.
       * </pre>
       *
       * <code>optional string usb_printer_manufacturer = 1;</code>
       * @return The usbPrinterManufacturer.
       */
      @java.lang.Override
      public java.lang.String getUsbPrinterManufacturer() {
        return instance.getUsbPrinterManufacturer();
      }
      /**
       * <pre>
       * The detected printer manufacuter name.
       * </pre>
       *
       * <code>optional string usb_printer_manufacturer = 1;</code>
       * @return The bytes for usbPrinterManufacturer.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUsbPrinterManufacturerBytes() {
        return instance.getUsbPrinterManufacturerBytes();
      }
      /**
       * <pre>
       * The detected printer manufacuter name.
       * </pre>
       *
       * <code>optional string usb_printer_manufacturer = 1;</code>
       * @param value The usbPrinterManufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setUsbPrinterManufacturer(
          java.lang.String value) {
        copyOnWrite();
        instance.setUsbPrinterManufacturer(value);
        return this;
      }
      /**
       * <pre>
       * The detected printer manufacuter name.
       * </pre>
       *
       * <code>optional string usb_printer_manufacturer = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsbPrinterManufacturer() {
        copyOnWrite();
        instance.clearUsbPrinterManufacturer();
        return this;
      }
      /**
       * <pre>
       * The detected printer manufacuter name.
       * </pre>
       *
       * <code>optional string usb_printer_manufacturer = 1;</code>
       * @param value The bytes for usbPrinterManufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setUsbPrinterManufacturerBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUsbPrinterManufacturerBytes(value);
        return this;
      }

      /**
       * <pre>
       * The detected printer model name.
       * </pre>
       *
       * <code>optional string usb_printer_model = 2;</code>
       * @return Whether the usbPrinterModel field is set.
       */
      @java.lang.Override
      public boolean hasUsbPrinterModel() {
        return instance.hasUsbPrinterModel();
      }
      /**
       * <pre>
       * The detected printer model name.
       * </pre>
       *
       * <code>optional string usb_printer_model = 2;</code>
       * @return The usbPrinterModel.
       */
      @java.lang.Override
      public java.lang.String getUsbPrinterModel() {
        return instance.getUsbPrinterModel();
      }
      /**
       * <pre>
       * The detected printer model name.
       * </pre>
       *
       * <code>optional string usb_printer_model = 2;</code>
       * @return The bytes for usbPrinterModel.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUsbPrinterModelBytes() {
        return instance.getUsbPrinterModelBytes();
      }
      /**
       * <pre>
       * The detected printer model name.
       * </pre>
       *
       * <code>optional string usb_printer_model = 2;</code>
       * @param value The usbPrinterModel to set.
       * @return This builder for chaining.
       */
      public Builder setUsbPrinterModel(
          java.lang.String value) {
        copyOnWrite();
        instance.setUsbPrinterModel(value);
        return this;
      }
      /**
       * <pre>
       * The detected printer model name.
       * </pre>
       *
       * <code>optional string usb_printer_model = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsbPrinterModel() {
        copyOnWrite();
        instance.clearUsbPrinterModel();
        return this;
      }
      /**
       * <pre>
       * The detected printer model name.
       * </pre>
       *
       * <code>optional string usb_printer_model = 2;</code>
       * @param value The bytes for usbPrinterModel to set.
       * @return This builder for chaining.
       */
      public Builder setUsbPrinterModelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUsbPrinterModelBytes(value);
        return this;
      }

      /**
       * <pre>
       * The usb vendor id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_vendor_id = 3;</code>
       * @return Whether the usbVendorId field is set.
       */
      @java.lang.Override
      public boolean hasUsbVendorId() {
        return instance.hasUsbVendorId();
      }
      /**
       * <pre>
       * The usb vendor id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_vendor_id = 3;</code>
       * @return The usbVendorId.
       */
      @java.lang.Override
      public int getUsbVendorId() {
        return instance.getUsbVendorId();
      }
      /**
       * <pre>
       * The usb vendor id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_vendor_id = 3;</code>
       * @param value The usbVendorId to set.
       * @return This builder for chaining.
       */
      public Builder setUsbVendorId(int value) {
        copyOnWrite();
        instance.setUsbVendorId(value);
        return this;
      }
      /**
       * <pre>
       * The usb vendor id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_vendor_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsbVendorId() {
        copyOnWrite();
        instance.clearUsbVendorId();
        return this;
      }

      /**
       * <pre>
       * The usb model id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_model_id = 4;</code>
       * @return Whether the usbModelId field is set.
       */
      @java.lang.Override
      public boolean hasUsbModelId() {
        return instance.hasUsbModelId();
      }
      /**
       * <pre>
       * The usb model id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_model_id = 4;</code>
       * @return The usbModelId.
       */
      @java.lang.Override
      public int getUsbModelId() {
        return instance.getUsbModelId();
      }
      /**
       * <pre>
       * The usb model id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_model_id = 4;</code>
       * @param value The usbModelId to set.
       * @return This builder for chaining.
       */
      public Builder setUsbModelId(int value) {
        copyOnWrite();
        instance.setUsbModelId(value);
        return this;
      }
      /**
       * <pre>
       * The usb model id of the printer.
       * </pre>
       *
       * <code>optional int32 usb_model_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsbModelId() {
        copyOnWrite();
        instance.clearUsbModelId();
        return this;
      }

      /**
       * <pre>
       * The value reported as a printer's printer-make-and-model attribute.
       * </pre>
       *
       * <code>optional string ipp_make_and_model = 5;</code>
       * @return Whether the ippMakeAndModel field is set.
       */
      @java.lang.Override
      public boolean hasIppMakeAndModel() {
        return instance.hasIppMakeAndModel();
      }
      /**
       * <pre>
       * The value reported as a printer's printer-make-and-model attribute.
       * </pre>
       *
       * <code>optional string ipp_make_and_model = 5;</code>
       * @return The ippMakeAndModel.
       */
      @java.lang.Override
      public java.lang.String getIppMakeAndModel() {
        return instance.getIppMakeAndModel();
      }
      /**
       * <pre>
       * The value reported as a printer's printer-make-and-model attribute.
       * </pre>
       *
       * <code>optional string ipp_make_and_model = 5;</code>
       * @return The bytes for ippMakeAndModel.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIppMakeAndModelBytes() {
        return instance.getIppMakeAndModelBytes();
      }
      /**
       * <pre>
       * The value reported as a printer's printer-make-and-model attribute.
       * </pre>
       *
       * <code>optional string ipp_make_and_model = 5;</code>
       * @param value The ippMakeAndModel to set.
       * @return This builder for chaining.
       */
      public Builder setIppMakeAndModel(
          java.lang.String value) {
        copyOnWrite();
        instance.setIppMakeAndModel(value);
        return this;
      }
      /**
       * <pre>
       * The value reported as a printer's printer-make-and-model attribute.
       * </pre>
       *
       * <code>optional string ipp_make_and_model = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIppMakeAndModel() {
        copyOnWrite();
        instance.clearIppMakeAndModel();
        return this;
      }
      /**
       * <pre>
       * The value reported as a printer's printer-make-and-model attribute.
       * </pre>
       *
       * <code>optional string ipp_make_and_model = 5;</code>
       * @param value The bytes for ippMakeAndModel to set.
       * @return This builder for chaining.
       */
      public Builder setIppMakeAndModelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIppMakeAndModelBytes(value);
        return this;
      }

      /**
       * <pre>
       * A true value means that the user provided their own PPD.
       * </pre>
       *
       * <code>optional bool user_ppd = 6;</code>
       * @return Whether the userPpd field is set.
       */
      @java.lang.Override
      public boolean hasUserPpd() {
        return instance.hasUserPpd();
      }
      /**
       * <pre>
       * A true value means that the user provided their own PPD.
       * </pre>
       *
       * <code>optional bool user_ppd = 6;</code>
       * @return The userPpd.
       */
      @java.lang.Override
      public boolean getUserPpd() {
        return instance.getUserPpd();
      }
      /**
       * <pre>
       * A true value means that the user provided their own PPD.
       * </pre>
       *
       * <code>optional bool user_ppd = 6;</code>
       * @param value The userPpd to set.
       * @return This builder for chaining.
       */
      public Builder setUserPpd(boolean value) {
        copyOnWrite();
        instance.setUserPpd(value);
        return this;
      }
      /**
       * <pre>
       * A true value means that the user provided their own PPD.
       * </pre>
       *
       * <code>optional bool user_ppd = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserPpd() {
        copyOnWrite();
        instance.clearUserPpd();
        return this;
      }

      /**
       * <pre>
       * The identifier for PPDs from our serving system.
       * </pre>
       *
       * <code>optional string ppd_identifier = 7;</code>
       * @return Whether the ppdIdentifier field is set.
       */
      @java.lang.Override
      public boolean hasPpdIdentifier() {
        return instance.hasPpdIdentifier();
      }
      /**
       * <pre>
       * The identifier for PPDs from our serving system.
       * </pre>
       *
       * <code>optional string ppd_identifier = 7;</code>
       * @return The ppdIdentifier.
       */
      @java.lang.Override
      public java.lang.String getPpdIdentifier() {
        return instance.getPpdIdentifier();
      }
      /**
       * <pre>
       * The identifier for PPDs from our serving system.
       * </pre>
       *
       * <code>optional string ppd_identifier = 7;</code>
       * @return The bytes for ppdIdentifier.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPpdIdentifierBytes() {
        return instance.getPpdIdentifierBytes();
      }
      /**
       * <pre>
       * The identifier for PPDs from our serving system.
       * </pre>
       *
       * <code>optional string ppd_identifier = 7;</code>
       * @param value The ppdIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setPpdIdentifier(
          java.lang.String value) {
        copyOnWrite();
        instance.setPpdIdentifier(value);
        return this;
      }
      /**
       * <pre>
       * The identifier for PPDs from our serving system.
       * </pre>
       *
       * <code>optional string ppd_identifier = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPpdIdentifier() {
        copyOnWrite();
        instance.clearPpdIdentifier();
        return this;
      }
      /**
       * <pre>
       * The identifier for PPDs from our serving system.
       * </pre>
       *
       * <code>optional string ppd_identifier = 7;</code>
       * @param value The bytes for ppdIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setPpdIdentifierBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPpdIdentifierBytes(value);
        return this;
      }

      /**
       * <pre>
       * The event for which this was recorded.
       * </pre>
       *
       * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
       * @return Whether the eventType field is set.
       */
      @java.lang.Override
      public boolean hasEventType() {
        return instance.hasEventType();
      }
      /**
       * <pre>
       * The event for which this was recorded.
       * </pre>
       *
       * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
       * @return The eventType.
       */
      @java.lang.Override
      public org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType getEventType() {
        return instance.getEventType();
      }
      /**
       * <pre>
       * The event for which this was recorded.
       * </pre>
       *
       * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
       * @param value The enum numeric value on the wire for eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventType(org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType value) {
        copyOnWrite();
        instance.setEventType(value);
        return this;
      }
      /**
       * <pre>
       * The event for which this was recorded.
       * </pre>
       *
       * <code>optional .metrics.PrinterEventProto.EventType event_type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventType() {
        copyOnWrite();
        instance.clearEventType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:metrics.PrinterEventProto)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "usbPrinterManufacturer_",
              "usbPrinterModel_",
              "usbVendorId_",
              "usbModelId_",
              "ippMakeAndModel_",
              "userPpd_",
              "ppdIdentifier_",
              "eventType_",
              org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.EventType.internalGetVerifier(),
            };
            java.lang.String info =
                "\u0001\b\u0000\u0001\u0001\b\b\u0000\u0000\u0000\u0001\u1008\u0000\u0002\u1008\u0001" +
                "\u0003\u1004\u0002\u0004\u1004\u0003\u0005\u1008\u0004\u0006\u1007\u0005\u0007\u1008" +
                "\u0006\b\u100c\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:metrics.PrinterEventProto)
    private static final org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto DEFAULT_INSTANCE;
    static {
      PrinterEventProto defaultInstance = new PrinterEventProto();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PrinterEventProto.class, defaultInstance);
    }

    public static org.chromium.components.metrics.PrinterEventProtos.PrinterEventProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PrinterEventProto> PARSER;

    public static com.google.protobuf.Parser<PrinterEventProto> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
