// TextInputAction.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/base/ime/mojom/ime_types.mojom
//

package org.chromium.ui.mojom;

import androidx.annotation.IntDef;

public final class TextInputAction {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        TextInputAction.DEFAULT,
        TextInputAction.ENTER,
        TextInputAction.DONE,
        TextInputAction.GO,
        TextInputAction.NEXT,
        TextInputAction.PREVIOUS,
        TextInputAction.SEARCH,
        TextInputAction.SEND})
    public @interface EnumType {}

    public static final int DEFAULT = 0;
    public static final int ENTER = 1;
    public static final int DONE = 2;
    public static final int GO = 3;
    public static final int NEXT = 4;
    public static final int PREVIOUS = 5;
    public static final int SEARCH = 6;
    public static final int SEND = 7;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 7;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 7;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private TextInputAction() {}
}